// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjOvdmoUXlZhQ3p6KjrmHw398H0Te01GQ',
    appId: '1:764596656844:web:fda6ae820132470ec24069',
    messagingSenderId: '764596656844',
    projectId: 'ev-radar-app',
    authDomain: 'ev-radar-app.firebaseapp.com',
    storageBucket: 'ev-radar-app.firebasestorage.app',
    measurementId: 'G-F3HV2X60NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAZRhHrlRmKnyMpNRx70PE0GZ-dJ34RgY',
    appId: '1:764596656844:android:a026dbdd6dc101b6c24069',
    messagingSenderId: '764596656844',
    projectId: 'ev-radar-app',
    storageBucket: 'ev-radar-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjAmHYm5rwns4tY_oEOeoszgZkl5Pkjxs',
    appId: '1:764596656844:ios:28e3ce809ecad70cc24069',
    messagingSenderId: '764596656844',
    projectId: 'ev-radar-app',
    storageBucket: 'ev-radar-app.firebasestorage.app',
    iosBundleId: 'com.example.evRadar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjAmHYm5rwns4tY_oEOeoszgZkl5Pkjxs',
    appId: '1:764596656844:ios:28e3ce809ecad70cc24069',
    messagingSenderId: '764596656844',
    projectId: 'ev-radar-app',
    storageBucket: 'ev-radar-app.firebasestorage.app',
    iosBundleId: 'com.example.evRadar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjOvdmoUXlZhQ3p6KjrmHw398H0Te01GQ',
    appId: '1:764596656844:web:5a0d0e30f23fc0fdc24069',
    messagingSenderId: '764596656844',
    projectId: 'ev-radar-app',
    authDomain: 'ev-radar-app.firebaseapp.com',
    storageBucket: 'ev-radar-app.firebasestorage.app',
    measurementId: 'G-Y1VWJRQELC',
  );
}
